### ISSUE TITLE
Instructions for setting up LocalBox

### ISSUE THREAD

**Issue by amitjoy** [shroominic/codebox-api#11]
Could you kindly provide the detailed instructions for using LocalBox for testing purposes? Currently, it requires WebSockets too which I am not sure why and how to setup?

**Comment by vmwsree** [comment]
Is this project live?

**Comment by shroominic** [comment]
Hey @amitjoy will release a better documentation this should help but I dont think you need to worry about web sockets...
What specifically are you trying to do?
WebSockets are for communicating with the JupyterKernel, which is started to execute your python code.
If you have a better idea feel free to open a PR with your implementation.

It should just work if you use the CodeBox without an CODEBOX_API_KEY.
Checkout the codebox-api/examples and let me know if you still have a problem!

**Comment by shroominic** [comment]
@vmwsree @amitjoy sorry for the late answer I checked this issue but then forgot to respond 😅
I currently doing this all alone and working on multiple projects in parallel (see my [website](https://shroominic.com)) but I maybe consider building a team soon to ensure better support and faster growth!
But still the CodeBoxAPI service is running (see [auto test action](https://github.com/shroominic/codebox-api/actions/workflows/auto-tests.yml)) and people have deployed with it so the project is running kind of autonomous 🤖
