### ISSUE TITLE
Start the codebox with the requirements.txt

### ISSUE THREAD

**Issue by anhdtd** [shroominic/codebox-api#4]
Thanks for sharing your project but I found that when run LLM it always installing some package at first and consuming unnecessary tokens, is it possible to start the codebox (localbox is oke) with pre-defined list of packages in requirements.txt file for example?

**Comment by shroominic** [comment]
You can call codebox.install("package_name") which does not consume any tokens. There is no requirements install yet but you can just call this method for every package using a python for loop.

**Comment by shroominic** [comment]
When you use LocalBox (when using without an API key) it uses your current Python environment so you can also install anything you need in advance :)
