### ISSUE TITLE
How can I get an api key of codebox?

### ISSUE THREAD

**Issue by whitesay** [shroominic/codebox-api#5]

**Comment by shroominic** [comment]
https://pay.codeboxapi.com/b/00g3e6dZX2fTg0gaEE?prefilled_promo_code=BETA
You can use this **beta** testing subscription. After the payment is complete you will receive and **email with the API key.** In future you can convert this to higher tiers and also a dev dashboard will be available to see your usage like openai platform.

**Comment by whitesay** [comment]
已收到您的信件！

**Comment by jiaqi-fmc** [comment]
I'd also like to get an API key. Can I also use the subscription above? https://pay.codeboxapi.com/b/00g3e6dZX2fTg0gaEE?prefilled_promo_code=BETA

**Comment by shroominic** [comment]
> I'd also like to get an API key. Can I also use the subscription above? https://pay.codeboxapi.com/b/00g3e6dZX2fTg0gaEE?prefilled_promo_code=BETA

Yeah you can use the same link.
Is basically a login system so you put your details and the backend creates an account and sends you an email :D

**Comment by zhangzhejian** [comment]
After upgrading, how many connections are allowed? It seems that only one is allowed now?

**Comment by shroominic** [comment]
Currently limited to 5 but the backend is autoscaling so we can talk about any other limit you need and I will manually adjust it :D
